-- 코드를 입력하세요
SELECT DISTINCT o.USER_ID, o.PRODUCT_ID
from ONLINE_SALE o, ONLINE_SALE s
where o.USER_ID=s.USER_ID and o.PRODUCT_ID=s.PRODUCT_ID and o.SALES_DATE!=s.SALES_DATE
order by o.USER_ID, o.PRODUCT_ID DESC